### PR TITLE
Change toStream to push the initial value

### PR DESCRIPTION
**Pull request by NetanelBasal**
- A stream should push the initial value.
- Remove import from a file that does not exist - `./when-async.ts`
- Add tests.

You have to consider it to be a BREAKING_CHANGE.

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Closes #82

**Comment by mweststrate** [comment]
@NetanelBasal if the default for `startImmediately`  would be change to false, this would be a non-breaking change, right?

**Comment by NetanelBasal** [comment]
Yes, but in my opinion, this should be the default behavior. When you have a  stream, usually you want to get the initial value, what do you think?

For example, when we want to show the observable data in the UI, we need to show the initial value.

**Comment by mweststrate** [comment]
Merged! Thanks :) I changed the default to `false`. I think that could be arguable if the consumer is not UI, but make a network request for example. but more important: it avoids this being a breaking change :). 

will release soon

**Pull request merged**
