### PR TITLE
update ci configuration and changelog

### PR DESCRIPTION
**Pull request by kuitos**
1. add changelog and bump version according to https://github.com/mobxjs/mobx-utils/pull/137
2. update ci configuration & add lint stage
3. fix lint errors in source code

### CODE REVIEW

**Comment by kuitos** [comment]
@daedalus28 I noticed that we publish this lib via manual script `publish.js`, should we use travis instead when we push a new tag and published automatically?

**Comment by mweststrate** [comment]
We could use the np package instead, but travis auto publish is hard given
the recent token issues? If you want publish permissions though thats no
problem!

Op do 19 jul. 2018 09:57 schreef Kuitos <notifications@github.com>:

**Comment by kuitos** [comment]
> but travis auto publish is hard given the recent token issues?
uh... Exactly I do know what the issue is, could you please explain it briefly?

**Comment by mweststrate** [comment]
If travis has the NPM publish tokens, one could create a PR on the
repository that grabs the token and sends it somewhere else, which would
happen automatically without by just opening the PR. (Probably there are
best practices to avoid this scenario)

Op do 19 jul. 2018 om 12:00 schreef Kuitos <notifications@github.com>:

**Comment by mweststrate** [comment]
Merge for now, as this is already a nice improvement, thanks!

@kuitos, if you want, I can give you maintainer rights so that you don't have to wait this long next time :)?

**Comment by kuitos** [comment]
@mweststrate cool! I'm glad to help maintain this library!😃

**Pull request merged**
