### PR TITLE
Enable TS strict mode

### PR DESCRIPTION
**Pull request by NaridaL**
src/tsconfig.json: set strict: true and fix errors

### CODE REVIEW

**Comment by NaridaL** [comment]
This should hopefully preempt other bugs like the one from #251 and make this library better for consumers who have strict mode on.

@mweststrate Do you want to give me npm access to mobx-utils so I don't have too keep bugging you to publish? 😃

**Comment by mweststrate** [comment]
Sure, AFK atm, but what is your npm username?

**Comment by NaridaL** [comment]
@mweststrate https://www.npmjs.com/~narida

**Comment by mweststrate** [comment]
Done, you should have publish rights now! The `./publish.js` script should
do all at once

**Comment by NaridaL** [comment]
@mweststrate Thanks, although I'm not sure what the point of the publish script is, considering updating the version, committing/tagging it and making sure the version doesn't exist already are all functions which yarn/npm do out-of-the-box.

**Pull request merged**
