### PR TITLE
viewmodel support for maps and arrays

### PR DESCRIPTION
**Pull request by vonovak**
hi! This PR should add support for maps and arrays. Let me know if it looks good or if I should remake something. 
Note the arrays cannot be modified in-place, but a new array has to be assigned to the viewModel, as it is done in tests. If it looks good, I'll add readme explanation before merge.

### CODE REVIEW

**Comment by mweststrate** [comment]
Looks good! Would you mind adding docs explaining how to deal with maps, arrays or nested objects? (always assign a fresh instance). Note that the docs are generated from the source.

**Comment by vonovak** [comment]
@mweststrate docs added :+1:

**Comment by vonovak** [comment]
I have a question though - there's a `dirtyMap` and `this.dirtyMap.set(key, true);` is called when setting a property. Then `this.dirtyMap.set(key, false);` when reseting it. Why not call `this.dirtyMap.delete(key);`? In that case, the `@observable isDirty` member would become 
````
@computed get isDirty(){
   return this.dirtyMap.size > 0
}
````

**Comment by mweststrate** [comment]
@vonovak the size is observable, so that should actually work :)

**Pull request merged**
