### PR TITLE
set started to false when calling lazyObservable.reset to allow further update to lazyObservable.

### PR DESCRIPTION
**Pull request by hepuxuan**
I am seeing a wired bug(or a feature, I am not 100% sure) where after I call lazyObservable.reset, lazyObservable ignores the fetch function and always return the initial value. I am not sure if that's expected but I would like to have lazyObservable continue to honor the fetch function after reset.
By setting started to false, the`current` function will call the fetch function when it's being invoked. I know this will be a breaking change but let me know what do you guys think.

### CODE REVIEW

**Comment by mweststrate** [comment]
I think the current behavior is incorrect indeed, and you've stumbled upon a bug, given that `refresh` also resets the `started` state. Would you mind adding a unit test to demonstrate the change in behavior just to be sure I've interpreted the problem and solution correctly?

Thanks

**Comment by hepuxuan** [comment]
absolutely, will do

**Comment by hepuxuan** [comment]
@mweststrate I've added the unit test, without this change, that test will fail since it always returns the initial value, but after setting started to false, that test passes

**Comment by hepuxuan** [comment]
@mweststrate do you mind check my updates when you have some time? my team is currently blocked on this issue. Thanks

**Comment by mweststrate** [comment]
Sorry for the late follow up! `ConferenceOverloadException` lol. Will release asap.

**Pull request merged**
