### PR TITLE
Fix ObservableGroupMap index out of bounds #255

### LINKED ISSUE #255: ObservableGroupMap grouperArrIndex out of bounds
Hi @NaridaL,

thanks for ObservableGroupMap. This is exactly what I needed and fortunately I found it here before implementing it myself. Very good timing. 😃

Unfortunately, there seems to be an issue in the current implementation (or I am holding it wrong). Sorry for not reporting this issue before the actual release which I just noticed now. I already run into it a few days ago but didn't find the time to minimize my reproduction code earlier nor to provide a fix.

Please consider this example:

    const { observable } = require("mobx");
    // const { ObservableGroupMap } = require("mobx-utils");
    const { ObservableGroupMap } = require("./ObservableGroupMap.js");

    const data = observable([
      { id: 1, a: "x" },
      { id: 2, a: "x" },
      { id: 3, a: "x" },
      { id: 4, a: "x" },
    ]);

    const ogm = new ObservableGroupMap(data, (e) => e.a);

    data.replace([{ id: 5, a: "x" }]);

I'm expecting this to work (and without the fourth item in the initial array it actually does).
However, I see this:

    /tmp/mobx-utils-ogm-issue/node_modules/mobx/lib/mobx.js:3355
                throw new Error("[mobx.array] Index out of bounds, " + index + " is larger than " + values.length);
                ^

    Error: [mobx.array] Index out of bounds, 3 is larger than 2
        at Array.set (/tmp/mobx-utils-ogm-issue/node_modules/mobx/lib/mobx.js:3355:19)
        at Object.set (/tmp/mobx-utils-ogm-issue/node_modules/mobx/lib/mobx.js:3023:33)
        at ObservableGroupMap._removeFromGroupArr (/tmp/mobx-utils-ogm-issue/ObservableGroupMap.js:159:22)
        at ObservableGroupMap._removeItem (/tmp/mobx-utils-ogm-issue/ObservableGroupMap.js:199:10)
        at /tmp/mobx-utils-ogm-issue/ObservableGroupMap.js:101:19
        at Object.transaction (/tmp/mobx-utils-ogm-issue/node_modules/mobx/lib/mobx.js:2816:23)
        at Array.<anonymous> (/tmp/mobx-utils-ogm-issue/ObservableGroupMap.js:98:16)
        at notifyListeners (/tmp/mobx-utils-ogm-issue/node_modules/mobx/lib/mobx.js:2988:21)
        at ObservableArrayAdministration.notifyArraySplice (/tmp/mobx-utils-ogm-issue/node_modules/mobx/lib/mobx.js:3202:13)
        at ObservableArrayAdministration.spliceWithArray (/tmp/mobx-utils-ogm-issue/node_modules/mobx/lib/mobx.js:3145:18)

### PR DESCRIPTION
**Pull request by bb**
Finish renaming from c13110ff6635cd3306b2d5bb30e1e9223cad3c9c.

Fixes #255

### CODE REVIEW

**Comment by bb** [comment]
The failing CI check (https://travis-ci.org/github/mobxjs/mobx-utils/builds/690512972#L320) seems unrelated to this PR.

Looks like it was introduced here: https://github.com/mobxjs/mobx-utils/commit/294e6a239852746f395e2c3b3e437a3a8cc8c8d3#diff-a92b7f050c8b346177d3ef7d7bf66be4R98.

**Comment by NaridaL** [comment]
@bb Thanks a lot for the fix! 

Yeah, it looks like I messed up when I renamed that field. I've gone ahead and refactored it to remove the `as any` casts which originally led to this mistake. I've also added your reproduction of the bug from #255 as a test case.

The CI failure is indeed unrelated, it looks like a test I added is flaky, I'll have a look at it later.

**Comment by bb** [comment]
Your refactoring made it much better and safer 👍

Just skimmed over it on the phone and like it.

Also good idea to add the failing test case. I was too tired and lazy.

**Comment by NaridaL** [comment]
@bb I published a 5.6.1 btw.

**Comment by bb** [comment]
Thanks a lot!

**Pull request merged**
