### PR TITLE
[CreateViewModel] - Add changedValues computed

### PR DESCRIPTION
**Pull request by ItamarShDev**
Fixed issue #171
Fixed issue #173

### CODE REVIEW

**Comment by ItamarShDev** [comment]
@mweststrate will be happy to get your thought :)

**Comment by mweststrate** [comment]
@ItamarShDev Looking good! Feel free to merge and release :). (Don't forget to update the changelog if you feel for the latter)

**Comment by ItamarShDev** [comment]
I would if I could @mweststrate

**Comment by mweststrate** [comment]
What is your npm username? Then I can add publish permissions! You have
already merge permissions, correct?

**Comment by ItamarShDev** [comment]
@mweststrate I can't merge here, it seems.

**Comment by mweststrate** [comment]
Wow, you weren't part of the org yet! Fixed :-D. You should now have a lot
more permissions everywhere. Sorry for not noticing that before!

**Comment by ItamarShDev** [comment]
@mweststrate No need to be sorry, I haven't even thought that I should be part of the org.

Thank you very much!

**Comment by ItamarShDev** [comment]
@mweststrate I prefer not to publish yet, I'd be happy to talk to you privately to validate that I understand the process clearly :)

**Comment by apsavin** [comment]
It would be great too see the changes on npm. :)

**Comment by mweststrate** [comment]
Released as 5.2.0!

**Pull request merged**
