### PR TITLE
updateableObservable

### PR DESCRIPTION
**Pull request by xaviergonz**
## updateableObservable

`updateableObservable` takes a non observable (or observable) value and turns it into
an observable that can be later updater with another non-observable (or observable) value
while trying to keep observable object references the same as much as possible.

Think of this as an observable with support for a "smart" deep merge.
This is useful for example when there's a big object coming from a back-end call,
yet you'd like to only trigger the minimum amount of reactions possibles (the ones with
actual changes).

The returned value will have two methods:

-   `get()` returns the value of the observable
-   `update(newValue)`: use this to update the current observable with the new value

The first parameter is the inital value the updateable observable should take.

The second parameter (update mode) can take one of the folowing values:

-   `"shallow"`: properties (primitives, objects, maps and arrays) are turned into a shallowly observable values
-   `"deep"`: properties (primitives, objects, maps and arrays) are turned into a deeply observable values
-   `{ deepProps: [keys] }`: like 'shallow', except some properties are turned into deep observables 'opt-in'

### Parameters

-   `initialValue` **T** 
-   `mode` **UpdateableObservableMode&lt;T>** 

### Examples

```javascript
const backendTodoList = ... // a plain array with list of plain todo objects
const todoList = updateableObservable(backendTodoList, "deep")
// new todo list comes from backend
todoList.update(newBackendTodoList)
// get the observable value
todoList.get()
```

Returns **IUpdateableObservable&lt;T>**

### CODE REVIEW

**Comment by xaviergonz** [comment]
For example, given
```
const uo = updateableObservable([{name: "mary"}, {name: "john"}], "deep")
const obsArr = uo.get()

uo.update([{name: "mary"}, {name: "james"}])
// obsArr, obsArr[0] and obsArr[1] will be the same ref as before the update, and are observables
// obsArr[1].name will be changed from "john" to "james"
```

**Comment by mweststrate** [comment]
Probably missing something, but wouldn't it be simpler to just have a `deepMerge(observableMap/Object/Array, newValue, options)`, so that no new data structure with it's own api is introduced?

**Comment by xaviergonz** [comment]
I guess that makes sense, though it is not strictly a deep merge, since props no longer in the original object would be deleted from the observable.
something like replaceMerge perhaps?

**Comment by mweststrate** [comment]
@xaviergonz ok to close this one for inactivity? Or did you still have plans for it?

**Comment by xaviergonz** [comment]
Still planning on it, just I forgot totally about it, sorry 🙏

**Comment by mweststrate** [comment]
Closing for now as this is a year old. Feel free to re-open later ;)

**Pull request closed without merging**
