### PR TITLE
Update README for fromPromise

### PR DESCRIPTION
**Pull request by hsrobbv**
* Remove deprecated `promise` property from returned object.
* Document the returned object's compatibility with `PromiseLike`
* Add example of chaining additional handlers to the returned `PromiseLike`

### CODE REVIEW

**Comment by mweststrate** [comment]
@hsrobbv thanks for the PR! But note that the API section of the Readme is generated from the code comments. Could you update the comments in `fromPromise.ts` instead? Thanks!

**Comment by hsrobbv** [comment]
A bit short on time, but I haven't forgotten about this... there seems to be some issue with the `when-async` module, I'll try to resolve on my branch when I get a chance this week.

**Comment by mweststrate** [comment]
I released a fix for that yesterday, so rebasing might resolve it :)

Op wo 27 sep. 2017 om 21:18 schreef hsrobbv <notifications@github.com>:

**Comment by hsrobbv** [comment]
I'm going to close this and re-open a PR based on the `fromPromise-readme-entry` branch

**Pull request closed without merging**
