### PR TITLE
ViewModel: local and computed values should have the same types as model

### PR DESCRIPTION
**Pull request by jordansexton**
I ran into a typing issue when inspecting `changedValues` because it's currently typed as `Map<any, any>` and doesn't reflect the keys and values of the model being wrapped by the ViewModel.

After this change, the compiled interfaces are:

```typescript
export interface IViewModel<T> {
    model: T;
    reset(): void;
    submit(): void;
    isDirty: boolean;
    changedValues: Map<keyof T, T[keyof T]>;
    isPropertyDirty(key: keyof T): boolean;
    resetProperty(key: keyof T): void;
}
export declare class ViewModel<T> implements IViewModel<T> {
    model: T;
    localValues: ObservableMap<keyof T, T[keyof T]>;
    localComputedValues: ObservableMap<keyof T, IComputedValue<T[keyof T]>>;
    readonly isDirty: boolean;
    readonly changedValues: Map<keyof T, T[keyof T]>;
    constructor(model: T);
    isPropertyDirty: (key: keyof T) => boolean;
    submit(): void;
    reset(): void;
    resetProperty(key: keyof T): void;
}
```

### CODE REVIEW

**Comment by jordansexton** [comment]
Currently:
```typescript
export interface IViewModel<T> {
    model: T;
    reset(): void;
    submit(): void;
    isDirty: boolean;
    isPropertyDirty(key: string): boolean;
    resetProperty(key: string): void;
}
export declare class ViewModel<T> implements IViewModel<T> {
    model: T;
    localValues: ObservableMap<any, any>;
    localComputedValues: ObservableMap<any, any>;
    readonly isDirty: boolean;
    readonly changedValues: Map<any, any>;
    constructor(model: T);
    isPropertyDirty: (key: string) => boolean;
    submit(): void;
    reset(): void;
    resetProperty(key: string): void;
}
```

**Comment by mweststrate** [comment]
note that the benefits of `Map<keyof T, T[keyof T]>` are limited, since the value and key types are still 'unrelated', the `T[keyof T]` will probably still create one big union of the different value types. But the keys are better indeed.

**Comment by jordansexton** [comment]
Would typing it as `ObservableMap<keyof T, T[keyof T]> & Partial<T>` help?

**Comment by mweststrate** [comment]
Nope, but I think we can leave it as is, just wanted to point out that it
isn't as powerful as it looks like at first sight :)

**Comment by mweststrate** [comment]
Released as 4.5.1

**Pull request merged**
