### PR TITLE
Fix from stream initialvalue type

### PR DESCRIPTION
**Pull request by NaridaL**
@KEIII You're right, the initial value wasn't typed correctly. I changed your PR a bit, as it isn't necessary to add a second type parameter to type it properly. Could you check this resolves problems with your use case?

### CODE REVIEW

**Comment by KEIII** [comment]
Thanks a lot for your review. Here is some code to describe type problem:
```typescript
const num$ = timer(1000).pipe(map(() => 42)); // we got 42 after 1000 ms after subscribe
const listener: IStreamListener<number> = fromStream(num$); // no initial value, no warnings
listener.current.toFixed(); // Runtime Error: TypeError: Cannot read property 'toFixed' of undefined
```
TypeScript say no type errors to this code. But real think is what listener.current is undefined (cause initialValue is undefined) before stream emits value.

**Comment by NaridaL** [comment]
@KEIII , OK, that should give the proper warning now, as the 1-arg fromSream is defined as:

`export function fromStream<T>(observable: IObservableStream<T>): IStreamListener<T | undefined>`

**Comment by NaridaL** [comment]
@mweststrate Can you publish a 5.6.0? Thanks!

**Comment by KEIII** [comment]
@NaridaL Nope, it's still no warning. The only way I was able to describe it properly was second type for initial value like #247

**Pull request merged**
